version: '3.8'
services:
  quiz-api:
    build:
      context: ./quiz-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - quiz-db:/app/db
    environment:
      FLASK_ENV: production
    networks:
      - quiz-network

  quiz-ui:
    build:
      context: ./quiz-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - quiz-network

volumes:
  quiz-db:
networks:
  quiz-network:
    driver: bridge